### ISSUE TITLE
AWS C9 not supported?

### ISSUE THREAD

**Issue by wfranzini** [wakatime/c9-wakatime#10]
Hi,

I'm evaluating AWS Cloud9 and it seems it's not supported by this plugin.
Do you plan to support AWS C9?

**Comment by wfranzini** [comment]
Hi, 

I've found that the instructions works also for AWS even if something is differente.

thanks for the plugin!

**Comment by SymbionicNigel** [comment]
@wfranzini hey could you point me towards the instructions to getting this working on aws's version of c9?

**Comment by gandarez** [comment]
Hey guys if you get the instructions please let me know to update the repository.
