### ISSUE TITLE
API key not saving

### ISSUE THREAD

**Issue by sladec** [wakatime/c9-wakatime#3]
Hi
Lately the API key is being asked for on every reload of C9 page ?
Operating System: X11 Linux x86_64
Web Browser: Chrome 49.0.2623.112

**Comment by sladec** [comment]
More info
from chrome inspector:

404 return from:
https://api.c9.io/user/persistent/wAhcDqPc4t+95pIe6EHDakJY6R8=?access_token=9cWyVK807D7VdhRakziy

then
https://wakatime.com/api/v1/users/signup/c9
returns:
{
  "errors": {
    "email": [
      "Email address already taken"
    ]
  }
}

Not sure if this will help ?
is it a c9 issue with user data storage ?

**Comment by mimibar** [comment]
I am also getting 

`XMLHttpRequest cannot load https://wakatime.com/api/v1/users/signup/c9. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ide.cs50.io' is therefore not allowed access. The response had HTTP status code 400.`

**Comment by alanhamlett** [comment]
Fixed with v3.0.1.

It will prompt you for an api key once, until you enter it from https://wakatime.com/settings then it will save to your user settings. The persistent settings are broken in production c9 it seems.
