### ISSUE TITLE
No Cloud9 Password, No wakatime

### ISSUE THREAD

**Issue by magikid** [wakatime/c9-wakatime#6]
When I try to install the Wakatime plugin for Cloud9, I'm prompted for my c9 password.  I don't have one since I've always logged into c9 through github.  I'd prefer to not set a password for my account, is there a work around for this situation?

**Comment by alanhamlett** [comment]
Maybe if they have an API Key or token that you could use instead of a password?

**Comment by alanhamlett** [comment]
Might be solved using the new manual install instructions.
