### ISSUE TITLE
Installing in C9.io not working

### ISSUE THREAD

**Issue by 07Gond** [wakatime/c9-wakatime#7]
**Problem**: 

I can't install Wakatime in my C9.io

**Steps:**
1. I have all Experimental SDK options activated.
2. I run the installer with: 
   `c9 install wakatime`
3. I receive this error message: 

> Unknown Error getting api.c9.io/packages/wakatime/versions/3.0.2/download?access_token=_myaccesstoken_

**Comment by alanhamlett** [comment]
Related to #2 but looks like a new error.

**Comment by JeffersonCN** [comment]
I'm facing the same problem.

EDIT:
Found [this ](https://community.c9.io/t/unable-to-install-wakatime/10457)post on Cloud9 Community forum that says it's an existing issue with plugin installs of any type.

**Comment by joilson-cisne** [comment]
The same still happening to me.

**Comment by alanhamlett** [comment]
Duplicate of #2. For now, use the manual install instructions. The manual instructions currently require running in debug mode, which is the only difference. Hopefully we can find a way to run manually installed plugins in non-debug mode.

**Comment by eminogrande** [comment]
How to enter the debug mode i don't get it - can somebody post a step by step guide how to get wakatime running on c9. The steps from the c9 forum doesn't seem to work.

**Comment by alanhamlett** [comment]
Add `?debug=true` to the url.

**Comment by stanwu** [comment]
Still error now...XD
stan**:~ $ c9 install wakatime
Unknown Error getting api.c9.io/packages/wakatime/versions/3.0.2/download?access_token=**********E:403
