### ISSUE TITLE
Is there a manual install option?

### ISSUE THREAD

**Issue by spences10** [wakatime/c9-wakatime#8]
Can you give instructions for a manual install of this?

**Comment by spences10** [comment]
My god that was fugly!

This is what I did to install manually

```
$ git clone https://github.com/wakatime/c9-wakatime
$ cd ~
$ cd .c9/plugins/wakatime
$ cp -a ~/workspace/c9-wakatime/. ~/.c9/plugins/wakatime/
```

Then used:

```
$ c9 run wakatime
```

Then got this output:

```
Permissions are:  world
Data is:  {
  "name": "wakatime",
  "description": "Metrics, insights, and time tracking automatically generated from your programming activity.",
  "version": "3.0.2",
  "author": "WakaTime",
  "contributors": [
    {
      "name": "Alan Hamlett",
      "email": "alan@wakatime.com"
    }
  ],
  "repository": {
    "type": "git",
    "url": "http://github.com/wakatime/c9-wakatime.git"
  },
  "plugins": {
    "wakatime": {
      "packagePath": "plugins/wakatime/wakatime"
    }
  },
  "engines": {
    "c9": ">=3.0.0"
  },
  "categories": [
    "miscellaneous"
  ],
  "license": "BSD-3-Clause",
  "licenses": [
    {
      "type": "BSD",
      "url": "https://github.com/wakatime/c9-wakatime/blob/master/LICENSE"
    }
  ],
  "installer": "install.js",
  "permissions": "world"
}
Permissions are:  world
WARNING: Description property in package.json will be ignored. README.md will be used.
Processing 3 files.
Compressing:  false
Done!
```

Then went to Tools>Developer>Start in Debug Mode then you are prompted to enter your wakatime API key

Super fiddly

Still doesn't work :thinking:

**Comment by alanhamlett** [comment]
Here are the manual install instructions. I'll add them to the readme soon:

1. Restart Cloud9 in Debug Mode (add `?debug=2` to the url)
2. `git clone https://github.com/wakatime/c9-wakatime.git`
3. `cd c9-wakatime`
4. `c9 install .`
5. `echo "export WAKATIME_HOME='~/workspace/'" >> ~/.profile`
6. `touch ~/workspace/.wakatime.cfg` 
7. Enter your API Key in the Cloud9 preferences. (might need to refresh the page first)

**Comment by spences10** [comment]
Thanks for this @alanhamlett, couple of things

After following the instructions I'm not prompted for the API key, this is after a refresh and restart, don't know where to go from here, there is a `.wakatime.cfg` file that has appeared in the same folder as the `c9-wakatime.git` repo 



Do we have to keep the editor in debug mode or can we switch back?

**Comment by alanhamlett** [comment]
It seems to only work in debug mode, not sure how to install plugins in regular mode without the Cloud9 Plugin API.

To enter your api key, go to this menu option:
Cloud9 -> Preferences -> User Settings -> WakaTime
